import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { AppSidebar } from "@/components/Sidebar";

import { auth } from "@/auth";
import { Session } from "next-auth";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="flex">
          <AppSidebar session={session as Session} />
          <div className="flex-1 overflow-auto p-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
